### ISSUE TITLE
Uygulama hatalı

### ISSUE THREAD

**Issue by OmerYigitYildiz** [yemrekocamese/odoo_error_log#1]
Açılmıyor böyle olur mu

**Comment by yemrekocamese** [comment]
__pycache__ dosyasından kaynaklı olabilir düzeltiliyor hemen.

**Comment by OmerYigitYildiz** [comment]
En kısa sürede düzeltilirse sevinirim. Teşekkürler.

**Comment by yemrekocamese** [comment]
yunus !!! model alanları elden geçecek
